#!/usr/bin/env bash
# generate-fnet-launchd-wrapper.sh
#
# Create a signed Mach-O wrapper binary for a macOS LaunchAgent so that
# System Settings > General > Login Items & Extensions shows
# "fnet-<name>" instead of the generic interpreter (python3, bash, etc.).
#
# The wrapper is a tiny C program that hard-codes the original command and
# arguments and exec()s them. It is ad-hoc signed so macOS treats it as a
# signed executable (hash-validated), which also lets the Background Items UI
# display the binary filename cleanly.
#
# Usage:
#   generate-fnet-launchd-wrapper.sh \
#     --name fnet-orchestrator-fleet-monitor \
#     --program /usr/local/bin/python3 \
#     --arg /Users/friasc/.../orchestrator-fleet-monitor.py \
#     --plist /Users/friasc/Library/LaunchAgents/com.frias.orchestrator-fleet-monitor.plist \
#     --reload

set -euo pipefail

NAME=""
PROGRAM=""
ARGS=()
PLIST=""
RELOAD=false
DEST_DIR="${HOME}/bin"

usage() {
  cat <<'EOF'
Usage: $0 --name fnet-<purpose> --program /path/to/interpreter \
          [--arg arg1] [--arg arg2] ... \
          --plist /path/to/agent.plist [--reload]

  --name     Base filename for the wrapper (recommend "fnet-<something>")
  --program  Absolute path to the executable to run
  --arg      One argument to pass (repeatable, order preserved)
  --plist    Absolute path to the LaunchAgent plist to rewrite
  --reload   Unload/reload the LaunchAgent after updating the plist
  --help     Show this help

Example:
  $0 --name fnet-orchestrator-fleet-monitor \
     --program /usr/local/bin/python3 \
     --arg /Users/friasc/.pi/agent/git/github.com/carlosfrias/pi-a2a-communication/scripts/orchestrator-fleet-monitor.py \
     --plist /Users/friasc/Library/LaunchAgents/com.frias.orchestrator-fleet-monitor.plist \
     --reload
EOF
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)    NAME="$2"; shift 2 ;;
    --program) PROGRAM="$2"; shift 2 ;;
    --arg)     ARGS+=("$2"); shift 2 ;;
    --plist)   PLIST="$2"; shift 2 ;;
    --reload)  RELOAD=true; shift ;;
    -h|--help) usage ;;
    *) echo "Unknown option: $1"; usage ;;
  esac
done

if [[ -z "$NAME" || -z "$PROGRAM" || -z "$PLIST" ]]; then
  echo "ERROR: --name, --program, and --plist are required." >&2
  usage
fi

if [[ ! -f "$PLIST" ]]; then
  echo "ERROR: plist not found: $PLIST" >&2
  exit 1
fi

if ! command -v clang >/dev/null 2>&1; then
  echo "ERROR: clang is required but not installed. Install Xcode Command Line Tools." >&2
  exit 1
fi

mkdir -p "$DEST_DIR"
DEST="$DEST_DIR/$NAME"
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# Serialize arguments for the Python helper.
export WRAPPER_PROGRAM="$PROGRAM"
export WRAPPER_DEST="$DEST"
export WRAPPER_ARGS_JSON=$(printf '%s\n' "${ARGS[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')

# Generate C source.
python3 - <<'PY' > "$TMP_DIR/wrapper.c"
import json, os

program = os.environ['WRAPPER_PROGRAM']
args = json.loads(os.environ['WRAPPER_ARGS_JSON'])

all_args = [program] + args
escaped = ',\n        '.join('"%s"' % a.replace('\\', '\\\\').replace('"', '\\"') for a in all_args)

print(f'''#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

/* Named LaunchAgent wrapper generated by generate-fnet-launchd-wrapper.sh */
int main(int argc, char *argv[]) {{
    (void)argc;
    (void)argv;
    const char *new_argv[] = {{
        {escaped},
        NULL
    }};
    execvp(new_argv[0], (char *const *)new_argv);
    perror("execvp failed");
    return 127;
}}
''')
PY

# Compile.
echo "Compiling $DEST ..."
clang -O2 -o "$DEST" "$TMP_DIR/wrapper.c"

# Ad-hoc sign.
echo "Ad-hoc signing $DEST ..."
codesign -s - -f "$DEST" >/dev/null 2>&1 || {
  echo "WARNING: codesign failed; binary is unsigned" >&2
}

if [[ ! -x "$DEST" ]]; then
  echo "ERROR: wrapper binary not executable: $DEST" >&2
  exit 1
fi

export WRAPPER_PLIST="$PLIST"

# Update the plist so ProgramArguments is just the wrapper binary.
echo "Updating $PLIST ..."
python3 - <<'PY'
import plistlib, os

path = os.environ['WRAPPER_PLIST']
dest = os.environ['WRAPPER_DEST']

with open(path, 'rb') as f:
    data = plistlib.load(f)

data['ProgramArguments'] = [dest]

with open(path, 'wb') as f:
    plistlib.dump(data, f)
PY

if $RELOAD; then
  echo "Reloading LaunchAgent $(basename "$PLIST" .plist) ..."
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load -w "$PLIST"
fi

echo "Done: $DEST"
echo "Verify with: codesign -dv $DEST"
